requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'RapidApp', '1.1005';
requires 'Catalyst::View::TT', '';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::View::Email';
requires 'DateTime';
requires 'DBIx::Class::TimeStamp';
requires 'SGML::DTDParse';
requires 'HTML::FormHandler';
requires 'HTML::TreeBuilder';
requires 'Data::GUID';
requires 'DateTime::Format::Strptime';
requires 'Config::General';
requires 'Catalyst::Plugin::StatusMessage';
requires 'HTML::FormHandler::Model::DBIC';
requires 'DBIx::Class::UUIDColumns';
requires 'Template::Stash::XS';
requires 'HTML::FormHandlerX::Field::noCAPTCHA';
requires 'Daemon::Control';
requires 'Catalyst::View::JSON';
requires 'LWP::UserAgent';
requires 'JSON';
requires 'MIME::Base64';
requires 'CatalystX::AuthenCookie';
