requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'RapidApp', '1.3102';
requires 'Catalyst::View::TT', '';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::View::Email';
requires 'Catalyst::Model::Adaptor';
requires 'Net::SMTP::SSL';
requires 'DateTime';
requires 'DBIx::Class::TimeStamp';
requires 'SQL::Abstract', '2';
requires 'SGML::DTDParse';
requires 'HTML::FormHandler';
requires 'HTML::TreeBuilder';
requires 'Data::GUID';
requires 'DateTime::Format::Strptime';
requires 'Config::General';
requires 'Catalyst::Plugin::StatusMessage';
requires 'HTML::FormHandler::Model::DBIC';
requires 'DBIx::Class::UUIDColumns';
requires 'Template::Stash::XS';
requires 'HTML::FormHandlerX::Field::noCAPTCHA';
requires 'Daemon::Control';
requires 'Catalyst::View::JSON';
requires 'Daemon::Control';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'JSON';
requires 'MIME::Base64';
requires 'CatalystX::AuthenCookie';
requires 'Catalyst::Plugin::StackTrace';
requires 'DBD::Pg', 3.18.0;
requires 'DateTime::Format::Pg';
requires 'List::Util';
requires 'Mojo::Base';
requires 'Telegram::Bot::Brain', '0.027';
requires 'DBIx::Class::InflateColumn::Serializer::JSON';
requires 'Text::Fuzzy';
requires 'Try::Tiny';
requires 'Text::CSV_XS';
requires 'Feature::Compat::Try';
requires 'Email::Sender::Simple';
requires 'Email::Sender::Transport::SMTP'; 
requires 'DBIx::Class::EasyFixture';
requires 'Time::HiRes';
requires 'Date::Holidays::GB';
requires 'Test::More';
requires 'Test::Exception';
requires 'DBIx::Class::InflateColumn::Boolean';
