version: '3.8'
services:
  access-system:
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ..:/opt
    depends_on: 
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: test
