#!/bin/sh

# Generated at Wed Apr 27 21:22:00 2016 with Daemon::Control 0.001008

### BEGIN INIT INFO
# Provides:          AccessSystem-API
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AccessSystem API
# Description:       AccessSystem API controls the AccessSystem API daemon.
### END INIT INFO`





if [ -x /home/pi/AccessSystem/script/accesssystem_api_daemon.pl ];
then
    /home/pi/AccessSystem/script/accesssystem_api_daemon.pl $1
else
    echo "Required program /home/pi/AccessSystem/script/accesssystem_api_daemon.pl not found!"
    exit 1;
fi
